In [18]:
import numpy as np

In [19]:
np.random.seed(38)

arr = np.random.rand(3,5)

arr

array([[0.38477312, 0.85970785, 0.94419964, 0.70282489, 0.6336341 ],
       [0.60596128, 0.20012684, 0.38738789, 0.25898316, 0.07460728],
       [0.28095697, 0.43843415, 0.48324904, 0.86848949, 0.52962938]])

In [20]:
# flatten array method 1

In [21]:
np.ravel(arr)

array([0.38477312, 0.85970785, 0.94419964, 0.70282489, 0.6336341 ,
       0.60596128, 0.20012684, 0.38738789, 0.25898316, 0.07460728,
       0.28095697, 0.43843415, 0.48324904, 0.86848949, 0.52962938])

In [22]:
arr.ravel()

array([0.38477312, 0.85970785, 0.94419964, 0.70282489, 0.6336341 ,
       0.60596128, 0.20012684, 0.38738789, 0.25898316, 0.07460728,
       0.28095697, 0.43843415, 0.48324904, 0.86848949, 0.52962938])

In [31]:
arr = np.arange(15).reshape(3,5)

print(arr)

arr_resize = np.resize(arr, (5,3))

print(arr_resize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [34]:
arr_2 = np.arange(20)

print(arr_2.reshape(-1, 2))

print(arr_2.reshape(5, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### stack vertically

In [52]:
arr = np.arange(6).reshape(2,3)

print(arr)

print(np.vstack((arr, arr)))

print(np.concatenate((arr, arr), 0))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


In [47]:
print(np.hstack((arr, arr)))

print(np.concatenate((arr, arr), 1))

[[0.40765231 0.89281693 0.23628623 0.21067825 0.40765231 0.89281693
  0.23628623 0.21067825]
 [0.35615192 0.52063632 0.58471016 0.61226111 0.35615192 0.52063632
  0.58471016 0.61226111]
 [0.29532836 0.10326149 0.99897124 0.03698089 0.29532836 0.10326149
  0.99897124 0.03698089]]
[[0.40765231 0.89281693 0.23628623 0.21067825 0.40765231 0.89281693
  0.23628623 0.21067825]
 [0.35615192 0.52063632 0.58471016 0.61226111 0.35615192 0.52063632
  0.58471016 0.61226111]
 [0.29532836 0.10326149 0.99897124 0.03698089 0.29532836 0.10326149
  0.99897124 0.03698089]]


### Splitting

In [61]:
arr = np.random.rand(2,2)

print(arr)

result_arr = np.hsplit(arr, 2)

for row in result_arr:
    print(row)
    


[[0.66672573 0.72851241]
 [0.48744125 0.41826915]]
[[0.66672573]
 [0.48744125]]
[[0.72851241]
 [0.41826915]]
[]
[[0.66672573 0.72851241]]
[[0.48744125 0.41826915]]


In [75]:

arr = np.random.rand(6,6)

print(arr)

result_arr_2 = np.vsplit(arr, 2

print(type(result_arr_2))

for row in result_arr_2:
    
    print(type(row))
    print(row)

[[0.7442066  0.70385925 0.07432136 0.01004888 0.09435092 0.3046244 ]
 [0.95488851 0.32407719 0.08642278 0.78118954 0.51857417 0.27045799]
 [0.40397913 0.24110543 0.77386654 0.48135556 0.59408226 0.24322064]
 [0.37815767 0.35188481 0.18577045 0.16087018 0.00878539 0.0667296 ]
 [0.50116921 0.08559099 0.65717487 0.19124128 0.0741819  0.42713702]
 [0.64992607 0.87638577 0.89055402 0.6715701  0.4777745  0.34038737]]
<class 'list'>
<class 'numpy.ndarray'>
[[0.7442066  0.70385925 0.07432136 0.01004888 0.09435092 0.3046244 ]
 [0.95488851 0.32407719 0.08642278 0.78118954 0.51857417 0.27045799]]
<class 'numpy.ndarray'>
[[0.40397913 0.24110543 0.77386654 0.48135556 0.59408226 0.24322064]
 [0.37815767 0.35188481 0.18577045 0.16087018 0.00878539 0.0667296 ]]
<class 'numpy.ndarray'>
[[0.50116921 0.08559099 0.65717487 0.19124128 0.0741819  0.42713702]
 [0.64992607 0.87638577 0.89055402 0.6715701  0.4777745  0.34038737]]
