In [67]:
#print numpy version 

import numpy as np

print(np.__version__)

1.20.2


In [68]:
# create a null vector of size 10

null_array = np.zeros(10)

print(null_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [69]:
interval_array = np.arange(10)

print(interval_array)

print(interval_array.ndim)
print(interval_array.shape)
print(interval_array.size)
print(interval_array.dtype)


[0 1 2 3 4 5 6 7 8 9]
1
(10,)
10
int64


### create np array from list / tuple

In [70]:
np_list = np.array([1,2,3])

np_tuple = np.array((1,2,3))

print(np_list)
print(np_tuple)

[1 2 3]
[1 2 3]


### Create 2 dimensional array

In [71]:
np.array([ [ 0, 1, 2], 
          [3, 4, 5] ])

array([[0, 1, 2],
       [3, 4, 5]])

### Create 3 dimensio# create 3-dimensional ndarray
### BEGIN SOLUTION
np.array(
    [ 
        [ 
            [ 0, 1, 2 ], 
            [ 3, 4, 5 ], 
            [ 6, 7, 8 ]
        ],
        [
            [9, 10, 11],
            [12, 13, 14],
            [15, 16, 17]
        ]
    ])nal array

In [72]:
# create 3-dimensional ndarray
np.array(
    [ 
        [ 
            [ 0, 1, 2 ], 
            [ 3, 4, 5 ], 
            [ 6, 7, 8 ]
        ],
        [
            [9, 10, 11],
            [12, 13, 14],
            [15, 16, 17]
        ]
    ])

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

### Defining dtype for array 

In [73]:
arr_1 = np.ones((2, 3), dtype="int32")

In [74]:
### Change dtype after definition

In [75]:
arr_1.astype('float64')

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create 2d array

In [76]:
arr_2d = np.arange(6).reshape(2,3)

for row in arr_2d:
    print(row)
    
arr_2d.shape

[0 1 2]
[3 4 5]


(2, 3)

In [77]:
print(arr_2d[0])



[0 1 2]


In [78]:
# use either index or tuple to access the index

In [79]:
print(arr_2d[1,1])
print(arr_2d[(1,1)])

4
4


### Basic Slicing

In [80]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
#takes all rows, and specific -1 column

arr_2d = np.arange(9).reshape(3,3)


print(arr_2d)
print(arr_2d.shape)
print(f"arr_2d[:-1]: {arr_2d[:-1]}")
print(f"arr_2d[1:]: {arr_2d[1:]}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
arr_2d[:-1]: [[0 1 2]
 [3 4 5]]
arr_2d[1:]: [[3 4 5]
 [6 7 8]]


# copy

In [85]:
arr = np.arange(6).reshape(2,3)

arr_view = arr

arr_view[1] = -1

print(arr)

[[ 0  1  2]
 [-1 -1 -1]]


In [86]:
arr = np.arange(6).reshape(2,3)

arr_copy = arr.copy()

arr_copy[1]  = -1

print(arr)

[[0 1 2]
 [3 4 5]]
