In [2]:
import torch
import numpy as np

In [3]:
#1. 데이터로부터 직접(directly) 생성하기

data = [[1, 2], [3, 4]]

x_data = torch.tensor(data)

In [6]:
#2. Numpy 배열로부터 생성하다
# array -> numpy array -> tensor array

np_data = np.array(data)

tensor_data = torch.from_numpy(np_data)

tensor([[1, 2],
        [3, 4]])
torch.int64


In [8]:
#3. 다른 텐서로부터 생성하기
x_ones = torch.ones_like(x_data)

print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)

print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2599, 0.1433],
        [0.0598, 0.2329]]) 



In [13]:
#4. 무작위(random) 또는 상수(constant) 값을 사용하기

#Define shape by tuple - ordered and unchanged array
shape = (2, 3,) #(2,3) and (2, 3,) is the same thing

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")



Random Tensor: 
 tensor([[0.0236, 0.6955, 0.5831],
        [0.2195, 0.3149, 0.3523]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [14]:
#Get shape, type, device

print(f"Shape: {rand_tensor.shape}")
print(f"Type: {rand_tensor.dtype}")
print(f"Device: {rand_tensor.device}")


Shape: torch.Size([2, 3])
Type: torch.float32
Device: cpu


In [15]:
# move tensor to gpu if exist
if torch.cuda.is_available():
    
    rand_tensor = rand_tensor.to("cuda")
    
else:
    
    print("GPU not exist")

GPU not exist


In [21]:
# indexing, slicing
new_shape = (4, 4)
new_tensor = torch.rand(new_shape)


print(new_tensor)

#first row
print(f"first row: {new_tensor[0, :]}")

#first column\
print(f"first column: {new_tensor[:, 0]}")

#last column
print(f"last column: {new_tensor[..., -1]}")
#print(f"last column: {new_tensor[:, -1]}")


tensor([[0.7598, 0.0644, 0.5755, 0.9508],
        [0.3565, 0.3936, 0.3436, 0.4032],
        [0.1633, 0.0621, 0.4909, 0.2786],
        [0.7402, 0.1851, 0.7988, 0.9122]])
first row: tensor([0.7598, 0.0644, 0.5755, 0.9508])
first column: tensor([0.7598, 0.3565, 0.1633, 0.7402])
last column: tensor([0.9508, 0.4032, 0.2786, 0.9122])


In [24]:
# concatenation
# dim = 0 for concat on row
# dim = 1 for concat on column
t1 = torch.cat([new_tensor, new_tensor, new_tensor], dim=0)

print(t1)

tensor([[0.7598, 0.0644, 0.5755, 0.9508],
        [0.3565, 0.3936, 0.3436, 0.4032],
        [0.1633, 0.0621, 0.4909, 0.2786],
        [0.7402, 0.1851, 0.7988, 0.9122],
        [0.7598, 0.0644, 0.5755, 0.9508],
        [0.3565, 0.3936, 0.3436, 0.4032],
        [0.1633, 0.0621, 0.4909, 0.2786],
        [0.7402, 0.1851, 0.7988, 0.9122],
        [0.7598, 0.0644, 0.5755, 0.9508],
        [0.3565, 0.3936, 0.3436, 0.4032],
        [0.1633, 0.0621, 0.4909, 0.2786],
        [0.7402, 0.1851, 0.7988, 0.9122]])


In [26]:
tensor = rand_tensor

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.0006, 0.4837, 0.3400],
        [0.0482, 0.0992, 0.1241]])

In [27]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

2.1889402866363525 <class 'float'>


In [33]:
# in place operation 

one_tensor = torch.ones(2,2)


one_tensor.add_(5)

print(one_tensor)

tensor([[6., 6.],
        [6., 6.]])


In [35]:
# In CPU, tensor array and numpy array shares the same memory, 
# One changes will reflect in the other one too

array = np.array([[1,2], [3,4]])

tensor_array = torch.from_numpy(array)

tensor_array[0, 0] = -1


print(array)

print(tensor_array)

[[-1  2]
 [ 3  4]]
tensor([[-1,  2],
        [ 3,  4]])


In [37]:
# tensor to numpy

another_tensor = torch.ones((3,3))

another_numpy = another_tensor.numpy()

# numpy to tensor 

yet_another_tensor = torch.from_numpy(another_numpy)


print(yet_another_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
