In [6]:
import torch
tensor = torch.tensor([[1,2,3,4], [5,6,7,8]])

print(tensor)

tensor[:, :2] -= 2
tensor[:, 2:4] += 2

print(tensor)

tensor[tensor < 0] = 0

print(tensor)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[-1,  0,  5,  6],
        [ 3,  4,  9, 10]])
tensor([[ 0,  0,  5,  6],
        [ 3,  4,  9, 10]])
