In [1]:
import torch
tensor = torch.tensor([[1,2,3,4], [5,6,7,8]])

print(tensor)

Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [2]:
tensor[:, :2] -= 2

print(tensor)



tensor([[-1,  0,  3,  4],
        [ 3,  4,  7,  8]])


In [3]:
tensor[:, 2:4] += 2

print(tensor)


tensor([[-1,  0,  5,  6],
        [ 3,  4,  9, 10]])


In [4]:

tensor[tensor < 0] = 0
tensor[tensor > 9] = 9

print(tensor)

tensor([[0, 0, 5, 6],
        [3, 4, 9, 9]])
